### ISSUE TITLE
colorized output fails for some input when output is non EN

### ISSUE THREAD

**Issue by sumproxy** [jarun/google-cli#17]
`> googler -n 8 -c en -l ru LRU`
produces the following error:
```text
 1  Алгоритмы кэширования — Википедия Traceback (most recent call last):
  File "/Users/SumProxy/Applications/bin/googler", line 393, in <module>
    results = fetch_results()
  File "/Users/SumProxy/Applications/bin/googler", line 386, in fetch_results
    r.print_entry()
  File "/Users/SumProxy/Applications/bin/googler", line 159, in print_entry
    "\x1B[0m\n\x1B[93m%s\x1B[39m" % url)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 40-57: ordinal not in range(128)
```

**Comment by jarun** [comment]
Hi,

Which terminal emulator are you using? Also what's the python version?

In my case, with AltYo & Python 2.7.6, result show but some characters are shown as Unicode chars.
No issues at all with AltYo and Python 3.4.3.

Can you please confirm the versions?

**Comment by sumproxy** [comment]
Hi,
Seems like its an Emacs eshell issue, in Mac OS term this works as expected..
In both cases Python version used was 2.7.8

**Comment by jarun** [comment]
Will see what I can do here but not sure of the timeline right away :)

**Comment by sumproxy** [comment]
Take your time, it's not urgent ;)

**Comment by jarun** [comment]
In the meantime, you can install Python 3.x on your box and patch your installed copy of googler by adding the following on top of it:
`#!/usr/bin/python3`

Using python 3 by default might work fine. However, I can't make the same change because I have to support both Python versions for AUR.

**Comment by sumproxy** [comment]
FYI python3 didn't help.

**Comment by jarun** [comment]
Thanks for updating the result!

**Comment by shaggytwodope** [comment]
@sumproxy not able to replicate this at all, in fact works well in emacs eshell for me. I'm wondering if this is a locale issue. But you mentioned osx, so not sure how to address that at all being a linux only guy. Maybe check out http://superuser.com/questions/538357/utf-8-characters-in-emacs-only-in-term-ansi-term-multi-term-do-not-appear

**Comment by sumproxy** [comment]
@shaggytwodope you're right, it is a locale issue. Setting LANG in my env fixed it.
Thanks everyone!
