### ISSUE TITLE
AUR packages

### ISSUE THREAD

**Issue by Narrat** [jarun/google-cli#2]
Hello

Edit: I hope I didn't jump to conclusions with my assumption AUR maintainer == project owner

I noticed today your fork and that you added it to the AUR.
Why not retaining the name and instead contacting the cli-google AUR-package maintainer (Ok, that would be me). Back then I forked it too, but just made it just working again (plus port to python3) more or less.
If you stepped up and improve it, why not doing it under the original name?
In my opinion this could be done, as upstream is clearly unavailable.

Why am I writing this?
One package offering the functionality is imo enough for the AUR. So , if you want the stay with your fork name I would create a merge request for the cli-google PKGBUILD I maintain.
If you decide to go back to the original name I would drop the maintainer post and you could adopt it changing it to your maintained fork.

Best regards
Lex

**Comment by shaggytwodope** [comment]
I'am the person who placed in it the aur. Few things to note here... the idea of only placing things that are unique is moot. That would be like saying no wm's cause we have gnome.

More importantly, the cli-google aur package uses python3, and works differently. The package name is different, altho functionality is similar... this still sticks to aur rules. 

(also the https://github.com/Narrat/cli-google version is kinda broken for me, not sure if its just me tho)


Lastly... complaints with aur packages should be addressed with contact info in the pkgbuild. Not a github repo that may have nothing to dow ith the chap posting it in aur. (I do watch each repo tho so I guess it's rare? lol)

**Comment by Narrat** [comment]
Jeah, my mistake for opening it here, as i jumped to conclusions (lastly I jumped just on projects were maintainer and project leader were the same) *cough*

Despite the other points. Just a suggestion, as my maintained package is clearly inferior and could be replaced. THe major difference is just the python2 vs python3 thing
