### ISSUE TITLE
Change bug report info in help.

### ISSUE THREAD

**Issue by shaggytwodope** [jarun/google-cli#6]
The info returned from simply running google gives

Copyright (C) 2008 Henri Hakkinen.
Report bugs to <henux@users.sourceforge.net>.

While the copyright is entirely fine, I think the report bugs bit should point the github here, or another email address. Since the project is basicly a fork at this point. And he should not be responsable for bugs.

**Comment by jarun** [comment]
Can you please confirm if you pulled the latest files?

Here's what I see:

arun@Tux~> google
Usage: google [OPTIONS] KEYWORDS...
Performs a Google search and prints the results to stdout.

Options
  -s N     start at the Nth result
  -n N     show N results (default 10)
  -l LANG  display in language LANG, such as fi for Finnish
  -C       disable color output
  -j       open the first result in a web browser
  -f MIME  search for specific file type
  -t dN    time limit search [e.g. d5: 5 days, w5: 5 weeks, m5: 5 months, y5: 5 years]

Keys
  n, p     press 'n' or 'p' and Enter to navigate forward and backward

Copyright (C) 2008 Henri Hakkinen.
Modified (2015) by Arun Prakash Jana <engineerarun@gmail.com>
Report bugs to https://github.com/jarun/google-cli/issues
arun@Tux~> cd DEVEL/google-cli/
arun@Tux~/D/google-cli> grep -nr henux
ChangeLog:19:2008-10-16  Henri Häkkinen  <henux@users.sourceforge.net>
ChangeLog:24:2008-10-15  Henri Häkkinen  <henux@users.sourceforge.net>
ChangeLog:31:2008-10-14  Henri Häkkinen  <henux@users.sourceforge.net>
ChangeLog:36:2008-10-13  Henri Häkkinen  <henux@users.sourceforge.net>
README.md:74:Initially I raised a pull request but I could see that the last change was made 7 years earlier. In addition, there is no GitHub activity from the original author (Henri Hakkinen: https://github.com/henux ) in past year. I have created this independent repo for the project with the name google-cli. Would love to push the changes back to original repo if the author contacts. I retained the original copyright information.
arun@Tux~/D/google-cli>

I can only find the email ID in the ChangeLog. Please verify once again with the latest codebase.

**Comment by shaggytwodope** [comment]
Silly thing, was using an older file from a dif fork. Sorry about that. No worries on the issue. But another question python3 port solid enough now? (so I can edit aur package to use python3)

**Comment by jarun** [comment]
My preliminary results seemed fine. Please spare me a few days to test more and confirm.
I will leave this issue open and get back to you on this thread once I'm sure it's stable enough.

**Comment by jarun** [comment]
I have completed the testing with new changes for Python 3.x. So far so good. Made a new baseline release (v1.1) which I believe is a good candidate for AUR. Please take a look at:
https://github.com/jarun/google-cli/releases/tag/v1.1

If the current set of capabilities look good to you please pick it up for AUR. The next road ahead with browser related changes is going to get bumpy and it might take some time before I move for a release.

**Comment by shaggytwodope** [comment]
Looks solid to me, the package for google-cli, and google-cli-git been changed to use default python now. (python3 on arch)

Thanks for letting me know dev status mate.

**Comment by jarun** [comment]
Thank you for finding it a place in AUR!
Closing the issue.

**Comment by jarun** [comment]
Just released version 1.2 with several new features. Check it out!  
https://github.com/jarun/google-cli/releases/tag/v1.2

**Comment by shaggytwodope** [comment]
Updated to 1.2 release. Great work.

**Comment by jarun** [comment]
Thank you!

**Comment by shaggytwodope** [comment]
In light of the renaming from google to googler, would you prefer the aur packages get renamed? As they are currently named google-cli.
Also if you can make a new tagged release that'd be great.

**Comment by jarun** [comment]
The name of the package remains google-cli. Only the utility name has been changed to googler from google. So no change required in AUR.
I will release a new version (probably 1.5) soon. Please hold till I test the incremental search implementation.

**Comment by jarun** [comment]
Version 1.5 released with incremental search.

**Comment by jarun** [comment]
Hi,

Would you mind checking the latest dev version? Included readline to make arrow keys work on the input line... Tested myself. Just want to double check things work with python 2 and 3.

Many thanks in advance.
